
name: call reusable workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  call-reusable:
    uses: Ashwanthsri/github-actions/.github/workflows/build.yaml
    with:
      name: "Build JAR/WAR files"
      environment: "development"
    secrets:
      mySecret: ${{ secrets.MY_CUSTOM_SECRET }}
  
