
name: Call Reusable workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  call-reusable:
    uses: Ashwanthsri/github-actions/.github/workflows/build.yaml@main
    with:
      name: "Build JAR/WAR files"
      environment: "development"
    secrets:
      NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
      NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
  
